name: Build OpenSSL 3.5.0 for Linux and Windows

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build for Linux (x64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential perl wget

      - name: Download OpenSSL 3.5.0 source
        run: |
          wget https://github.com/openssl/openssl/archive/refs/tags/openssl-3.5.0.tar.gz
          tar -xzf openssl-3.5.0.tar.gz
          mv openssl-openssl-3.5.0 openssl-src

      - name: Build OpenSSL
        working-directory: ./openssl-src
        run: |
          ./Configure
          make -j$(nproc)

      - name: Upload Linux OpenSSL binary
        uses: actions/upload-artifact@v4
        with:
          name: openssl-linux
          path: openssl-src/apps/openssl

  build-windows:
    name: Build for Windows (x64)
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install NASM
        run: choco install nasm -y

      - name: Install Strawberry Perl
        run: choco install strawberryperl -y

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Download OpenSSL 3.5.0 source
        run: |
          Invoke-WebRequest -Uri "https://github.com/openssl/openssl/archive/refs/tags/openssl-3.5.0.tar.gz" -OutFile "openssl-3.5.0.tar.gz"
          tar -xzf openssl-3.5.0.tar.gz
          Move-Item openssl-openssl-3.5.0 openssl-src

      - name: List files in openssl-src
        run: Get-ChildItem -Path .\openssl-src
        shell: pwsh

      - name: Configure OpenSSL (generate Makefile)
        working-directory: ./openssl-src
        run: |
          perl Configure VC-WIN64A
          if (!(Test-Path Makefile)) {
            Write-Host "Makefile generation failed. Exiting."
            exit 1
          }
        shell: pwsh

      - name: Build OpenSSL
        working-directory: ./openssl-src
        run: nmake

      - name: Upload Windows OpenSSL binary
        uses: actions/upload-artifact@v4
        with:
          name: openssl-windows
          path: openssl-src/apps/openssl.exe
