name: Build OpenSSL 3.5 (Windows & Linux)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential perl wget

      - name: Download OpenSSL
        run: wget https://github.com/openssl/openssl/archive/refs/tags/openssl-3.5.0.tar.gz

      - name: Extract OpenSSL
        run: tar -xzf openssl-3.5.0.tar.gz

      - name: Build OpenSSL
        working-directory: openssl-openssl-3.5.0
        run: |
          ./config
          make -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openssl-linux-bin
          path: openssl-openssl-3.5.0/apps/openssl

  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Chocolatey dependencies
        run: |
          choco install nasm -y
          choco install strawberryperl -y
        shell: powershell

      - name: Download OpenSSL
        run: Invoke-WebRequest -Uri "https://github.com/openssl/openssl/archive/refs/tags/openssl-3.5.0.tar.gz" -OutFile "openssl-3.5.0.tar.gz"
        shell: powershell

      - name: Extract OpenSSL
        run: tar -xzf openssl-3.5.0.tar.gz

      - name: Build OpenSSL
        working-directory: openssl-openssl-3.5.0
        run: |
          perl Configure VC-WIN64A
          set PATH=C:\ProgramData\chocolatey\bin;C:\Strawberry\perl\bin;%PATH%
          nmake

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openssl-windows-bin
          path: openssl-openssl-3.5.0/apps/openssl.exe
