name: Debug OpenSSL Build

on:
  push:
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: 'true'
  ACTIONS_STEP_DEBUG: 'true'

jobs:
  linux-debug:
    name: Linux Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print system info & PATH
        run: |
          uname -a
          lsb_release -a || cat /etc/os-release
          echo ""
          echo "=== ENV / PATH ==="
          env
          echo "=== PATH only ==="
          echo $PATH
        shell: bash

      - name: Install & debug prerequisites + build
        run: |
          set -x
          sudo apt-get update -y
          sudo apt-get install -y build-essential nasm perl wget tar
          which nasm || echo "!!! nasm not on PATH !!!"
          nasm -v
          perl -v
          # fetch, unpack & list
          wget https://github.com/openssl/openssl/archive/refs/tags/openssl-3.5.0.tar.gz -O openssl.tar.gz
          tar -xzf openssl.tar.gz
          cd openssl-openssl-3.5.0
          pwd; ls -la
          # configure & make with max verbosity
          echo ">>> Configuring…"
          ./Configure linux-x86_64 2>&1 | tee configure.log
          echo ">>> Running make…"
          make -j$(nproc) VERBOSE=1 2>&1 | tee make.log
        shell: bash

  windows-debug:
    name: Windows Debug
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print system info & PATH
        shell: pwsh
        run: |
          Write-Host "=== OS & ARCH ==="
          (Get-CimInstance Win32_OperatingSystem).Caption
          Write-Host "Processor architecture:" $Env:PROCESSOR_ARCHITECTURE
          Write-Host ""
          Write-Host "=== ENV ==="
          Get-ChildItem Env: | Sort-Object Name
          Write-Host ""
          Write-Host "=== PATH only ==="
          Write-Host $Env:Path

      - name: Install & debug prerequisites + build
        shell: pwsh
        run: |
          # install nasm + perl
          choco install nasm -y --no-progress
          choco install strawberryperl -y --no-progress
          refreshenv

          Write-Host ""
          Write-Host "=== After install PATH ==="
          Write-Host $Env:Path

          # Verify
          Get-Command nasm -ErrorAction SilentlyContinue || Write-Host "!!! nasm NOT found !!!"
          nasm -v
          perl -v

          # enable PS debug trace
          Set-PSDebug -Trace 2

          # fetch/unpack
          Invoke-WebRequest -Uri "https://github.com/openssl/openssl/archive/refs/tags/openssl-3.5.0.tar.gz" -OutFile "openssl.tar.gz"
          tar -xzf openssl.tar.gz
          Rename-Item openssl-openssl-3.5.0 openssl-src
          cd openssl-src

          Write-Host ""
          Write-Host "=== In source dir ==="
          Get-Location
          dir

          # configure + capture logs
          Write-Host ">>> perl Configure VC-WIN64A"
          perl Configure VC-WIN64A 2>&1 | Tee-Object -FilePath configure.log
          Write-Host "Configure exit code: $LASTEXITCODE"

          Write-Host ">>> nmake"
          nmake /nologo /noprogress 2>&1 | Tee-Object -FilePath make.log
          Write-Host "Make exit code: $LASTEXITCODE"
        working-directory: ${{ github.workspace }}
