name: OpenSSL 3.5 (claude)

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        platform:
          - arch: win64
            os: windows-2022
            config: no-shared no-module --prefix=C:\OpenSSL --openssldir=C:\OpenSSL\ssl
          - arch: win32
            os: windows-2022
            config: no-shared no-module --prefix=C:\OpenSSL --openssldir=C:\OpenSSL\ssl
    runs-on: ${{ matrix.platform.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Download and Setup OpenSSL Source
      shell: cmd
      run: |
        echo Downloading OpenSSL 3.5.0...
        curl -L -o openssl.zip https://github.com/openssl/openssl/archive/refs/tags/openssl-3.5.0.zip
        echo Extracting archive...
        tar -xf openssl.zip
        echo Renaming directory...
        ren openssl-openssl-3.5.0 openssl
        echo Verifying directory exists...
        dir openssl
        
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.platform.arch }}
        
    - uses: ilammy/setup-nasm@v1
      with:
        platform: ${{ matrix.platform.arch }}
        
    - name: Setup Perl
      shell: cmd
      run: choco install strawberryperl -y
        
    - name: Configure
      shell: cmd
      run: |
        cd openssl
        if "${{ matrix.platform.arch }}"=="win64" (
          perl Configure VC-WIN64A ${{ matrix.platform.config }}
        ) else (
          perl Configure VC-WIN32 ${{ matrix.platform.config }}
        )
        
    - name: Build
      shell: cmd
      run: |
        cd openssl
        nmake
        
    - name: Test
      shell: cmd
      run: |
        cd openssl
        nmake test
      continue-on-error: true
        
    - name: Install
      shell: cmd
      run: |
        cd openssl
        nmake install
        
    - name: Create portable executable
      shell: cmd
      run: |
        echo Creating portable OpenSSL executable...
        copy C:\OpenSSL\bin\openssl.exe openssl.exe
        
        echo Testing portable executable...
        openssl.exe version
        
        mkdir portable-package
        copy openssl.exe portable-package\
        
        echo OpenSSL 3.5.0 Portable - %{{ matrix.platform.arch }}% > portable-package\README.txt
        echo ======================================= >> portable-package\README.txt
        echo. >> portable-package\README.txt
        echo This is a standalone portable version of OpenSSL 3.5.0 >> portable-package\README.txt
        echo No installation required - just run the executable. >> portable-package\README.txt
        echo. >> portable-package\README.txt
        echo Usage: openssl.exe [command] [options] >> portable-package\README.txt
        echo. >> portable-package\README.txt
        echo Examples: >> portable-package\README.txt
        echo   openssl.exe version >> portable-package\README.txt
        echo   openssl.exe list -digest-algorithms >> portable-package\README.txt
        echo   openssl.exe genrsa -out private.key 2048 >> portable-package\README.txt
        echo   openssl.exe req -new -x509 -key private.key -out cert.pem -days 365 >> portable-package\README.txt
        echo. >> portable-package\README.txt
        echo Platform: Windows ${{ matrix.platform.arch }} >> portable-package\README.txt
        echo Version: OpenSSL 3.5.0 >> portable-package\README.txt
        
    - name: Package binaries
      shell: cmd
      run: |
        cd C:\OpenSSL
        tar -czf %GITHUB_WORKSPACE%\openssl-3.5.0-${{ matrix.platform.arch }}-windows-full.tar.gz *
        
    - name: Create portable package
      shell: cmd
      run: |
        cd portable-package
        tar -czf %GITHUB_WORKSPACE%\openssl-3.5.0-${{ matrix.platform.arch }}-portable.zip *
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openssl-3.5.0-${{ matrix.platform.arch }}-packages
        path: |
          openssl-3.5.0-${{ matrix.platform.arch }}-windows-full.tar.gz
          openssl-3.5.0-${{ matrix.platform.arch }}-portable.zip
        retention-days: 90
