name: Windows NASM Debug

on:
  workflow_dispatch:

jobs:
  nasm-debug:
    runs-on: windows-2022
    env:
      ACTIONS_STEP_DEBUG: 'true'
      ACTIONS_RUNNER_DEBUG: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-install inspection
        shell: pwsh
        run: |
          Write-Host "=== ChocolateyInstall ===" $Env:ChocolateyInstall
          Write-Host "=== PATH before install ==="
          Write-Host $Env:Path
          Write-Host "`n=== Listing chocolatey shims ==="
          Get-ChildItem "$Env:ChocolateyInstall\bin"      -Force | Sort-Object Name | Format-Table Name,Length,LastWriteTime
          Get-ChildItem "$Env:ChocolateyInstall\shims"    -Force | Sort-Object Name | Format-Table Name,Length,LastWriteTime
          Write-Host "`n=== Listing nasm lib folder (if any) ==="
          if (Test-Path "$Env:ChocolateyInstall\lib\nasm") {
            Get-ChildItem "$Env:ChocolateyInstall\lib\nasm" -Recurse | Format-Table FullName,Length,LastWriteTime
          } else {
            Write-Host "No lib\\nasm folder present"
          }

      - name: Install NASM via CMD (debug & verbose)
        shell: cmd
        run: |
          choco install nasm -y --debug --verbose
          refreshenv

      - name: Post-install in CMD
        shell: cmd
        run: |
          echo ==== where nasm ====
          where nasm || echo NOT FOUND
          echo.
          echo ==== nasm -v ====
          nasm -v || echo FAILED

      - name: Post-install in PowerShell (with proper refresh)
        shell: pwsh
        run: |
          # import chocolatey profile then refresh
          Import-Module "$Env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          RefreshEnv

          Write-Host "`n=== PATH after RefreshEnv ==="
          Write-Host $Env:Path

          Write-Host "`n=== where.exe nasm ==="
          where.exe nasm

          Write-Host "`n=== nasm -v ==="
          nasm -v
